# Generated by Django 6.0.1 on 2026-04-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_deliveryemaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
